services:

  pihole:
    image: pihole/pihole:2025.11.1
    container_name: pihole
    hostname: ${PIHOLE_HOSTNAME}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      - TZ=${TZ:-America/Winnipeg}
      - FTLCONF_webserver_api_password=${PIHOLE_PWD}
      - FTLCONF_webserver_port=80
      - FTLCONF_dns_listeningMode=all
      - FTLCONF_misc_etc_dnsmasq_d=true
      - FTLCONF_dns_upstreams=${PIHOLE_DNS}
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - ${PWD}/volumes/pihole/etc:/etc/pihole
      - ${PWD}/volumes/pihole/dnsmasq:/etc/dnsmasq.d
      - ${PWD}/volumes/pihole/log:/var/log/pihole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
      - CAP_CHOWN
    restart: unless-stopped

  ts-pihole:
    profiles: ["disabled"] # temporary disable
    image: tailscale/tailscale
    container_name: ts-pihole
    depends_on:
      pihole:
        condition: service_started
        restart: true
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=${TS_EXTRA_ARGS}
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${PWD}/volumes/ts-pihole/lib:/var/lib
      - ${PWD}/config/ts-pihole:/config
    cap_add:
      - NET_ADMIN
    network_mode: service:pihole
    restart: unless-stopped
